groups:
  - title: Math for ML
    posts:
      - title: Linear algebra
        subhead: Vectors and matricies
        href: /math/linear-algebra.html
      - title: Differential calculus
        subhead: Derivatives & automatic differentiation
        href: /math/differential-calculus.html
      - title: Partial derivatives
        subhead: Gradient vectors & Jacobian matricies
        href: /math/partial-derivatives.html
  - title: ML topics
    posts:
      - title: Activation functions
        subhead: Sigmoid, ReLU, softmax and others
        href: /ml/activation-functions.html
      - title: Loss functions
        subhead: L₁ vs. L₂ regularization
        href: /ml/loss-functions.html
      - title: Backpropagation by hand
        subhead: Example with concrete numbers
        href: /ml/backprop-by-hand.html
      - title: Attention mechanism
        subhead: Scaled dot-product attention
        href: /ml/attention-mechanism.html
      - title: Transformers
        subhead: In equations
        href: /ml/transformers.html
  - title: Language models
    posts:
      - title: Benchmarks
        subhead: WinoGrande & HellaSwag
        href: /lm/benchmarks.html
      - title: Misc terms
        subhead: Zero-shot
        href: /lm/misc-terms.html
